### ISSUE TITLE
Permission denied with invoke 

### ISSUE THREAD

**Issue by ghost** [vector-sec/PSPy#1]
Just quickly testing this project out, used the pre-packed zip PSPy-PS6.0.0-alpha.18.zip and ran a test of it with the following payload.
```
{
  "executionArg": "-c",
  "executionPayload": "Get-Host"
}
```
however the output is classed as ' succeeded ' but with the following error.  

`"/bin/sh: /var/task/powershell: Permission denied\n"`

**Comment by vector-sec** [comment]
@steven-cuthill-otm Looks like adding a chmod +x for /var/task/powershell fixed it. I've updated the master branch to reflect this change. Give it a try and let me know how it works for you.

**Comment by ghost** [comment]
Yup that works fine now, I am noticing that modules are not loading correctly ( I have added the AWSPowerShell.NetCore to ~/Modules/AWSPowerShell.NetCore) however it looks like all the default ones are not loading. Just the basic ones that are part of the powershelgl binary. Could be possible that we have ACL issue on the models deirectory.


{
  "executionArg": "-c",
  "executionPayload": "Get-Module -ListAvailable ;get-command -Module AWSPowerShell.NetCore ; write-host \" END OF SCRIPT\" "
}

START RequestId: ed355326-9bb9-11e8-a024-6f9d31cd22d3 Version: $LATEST
write-host : The term 'write-host' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:72
+ ... lable ;get-command -Module AWSPowerShell.NetCore ; write-host " END O ...
+                                                        ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (write-host:String) [], CommandN 
   otFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

END RequestId: ed355326-9bb9-11e8-a024-6f9d31cd22d3
REPORT RequestId: ed355326-9bb9-11e8-a024-6f9d31cd22d3	Duration: 19923.84 ms	Billed Duration: 20000 ms 	Memory Size: 128 MB	Max Memory Used: 83 MB	



{
  "executionArg": "-c",
  "executionPayload": "Get-Module -ListAvailable"
}
START RequestId: 16df5f5e-9bba-11e8-b689-cf12e1752efa Version: $LATEST

END RequestId: 16df5f5e-9bba-11e8-b689-cf12e1752efa
REPORT RequestId: 16df5f5e-9bba-11e8-b689-cf12e1752efa	Duration: 14879.54 ms	Billed Duration: 14900 ms 	Memory Size: 128 MB	Max Memory Used: 83 MB

**Comment by vector-sec** [comment]
Interesting, I decided to go ahead and re-release PSPy with the latest stable version of PowerShell 6. You can grab this release zip from https://github.com/vector-sec/PSPy/releases/tag/6.0.3

Below is the output I received using your example execution payload with the new release.

```
START RequestId: <request-id> Version: $LATEST


    Directory: /var/task/Modules


ModuleType Version    Name                                ExportedCommands     
---------- -------    ----                                ----------------     
Manifest   1.1.0.0    Microsoft.PowerShell.Archive        {Compress-Archive,...
Manifest   3.0.0.0    Microsoft.PowerShell.Host           {Start-Transcript,...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clea...
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {Get-Credential, G...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Format-List, Form...
Script     1.1.7.0    PackageManagement                   {Find-Package, Get...
Script     1.6.0      PowerShellGet                       {Install-Module, F...
Script     0.0        PSDesiredStateConfiguration         {Generate-VersionI...
Script     1.2        PSReadLine                          {Get-PSReadlineKey...
 END OF SCRIPT



END RequestId: <request-id>
REPORT RequestId: <request-id>	Duration: 17114.85 ms	Billed Duration: 17200 ms 	Memory Size: 128 MB	Max Memory Used: 78 MB	
```

**Comment by ghost** [comment]
all fixed, also loaded the aws Powershell core module and that looks like it works fine too.
